### ISSUE TITLE
После остановки сервера игровые порты остаются занятыми

### ISSUE THREAD

**Issue by sOGriN** [svtz/tanks#26]
В итоге невозможно запустить вторую игру на том же компе

**Comment by svtz** [comment]
может, просто пересоздать NetworkManager?

**Comment by sOGriN** [comment]
Исправлено https://github.com/svtz/tanks/commit/f2dc92226a148501f92acce94eb066dbfc083c3d

**Comment by svtz** [comment]
У меня вопрос.  Вот этот класс сейчас не используется. Он не нужен, или есть какие-то планы?
https://github.com/svtz/tanks/commit/f2dc92226a148501f92acce94eb066dbfc083c3d#diff-0517aa9b7f63a621c4c4aba0fd3d5115

**Comment by sOGriN** [comment]
Были задумки, но оно че-то не так сработало, как я хотел, и пока висит

**Comment by svtz** [comment]
Я тогда его грохну, видимо. Потому как вычитал, что весь этот подоход к ui через GUILayout в коде - legacy, сейчас модно делать по-другому, и очень хочется это как минимум затестить.

**Comment by sOGriN** [comment]
Ок, мне вообще не нравится, как он сейчас работает

**Comment by svtz** [comment]
Грохнул в https://github.com/svtz/tanks/commit/bc1fbd4272951b684054c00972ecd26393cd0600
